# Generated by Django 3.2 on 2022-08-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('detalle', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos')),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=120)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.categoriaevento')),
                ('costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.costoevento')),
                ('modalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.modalidadevento')),
            ],
        ),
    ]
